ztest:
	@echo TEST 0
	../main<dat0
	@echo TEST 1
	../main<dat1
	@echo TEST 2
	../main<dat2
	@echo TEST 3
	../main<dat3
	@echo SUCCESS
test:
	@echo TEST 0
	../main<dat0
	@echo TEST 1
	../main<dat1
	@echo TEST 2
	../main<dat2
	@echo TEST 3
	../main<dat3
	@echo TEST 4
	../main<dat4
	@echo SUCCESS
